const mainCards = [
  [
    "space",
    "food",
    "animals",
    "body",
    "nature",
    "activities",
    "colors",
    "family",
  ],
  [
    "./images/categories/space-category.png",
    "./images/categories/food-category.png",
    "./images/categories/animals-category.png",
    "./images/categories/body-category.png",
    "./images/categories/nature-category.png",
    "./images/categories/activities-category.png",
    "./images/categories/colors-category.png",
    "./images/categories/family-category.png",
  ],
  [
    "./sounds/space-gb.mp3",
    "./sounds/food-gb.mp3",
    "./sounds/animal-gb.mp3",
    "./sounds/body-gb.mp3",
    "./sounds/nature-gb.mp3",
    "./sounds/activity-gb.mp3",
    "./sounds/color-gb.mp3",
    "./sounds/family-gb.mp3",
  ],
];
const cards = [
  [
    {
      category: "space",
      word: "rocket",
      translation: "რაკეტა",
      image: "./images/rocket.svg",
      audioSrc: "./sounds/rocket-gb.mp3",
    },
    {
      category: "space",
      word: "sun",
      translation: "მზე",
      image: "./images/sun.svg",
      audioSrc: "./sounds/sun-gb.mp3",
    },
    {
      category: "space",
      word: "moon",
      translation: "მთვარე",
      image: "./images/moon.svg",
      audioSrc: "./sounds/moon-gb.mp3",
    },
    {
      category: "space",
      word: "planet",
      translation: "პლანეტა",
      image: "./images/planet.svg",
      audioSrc: "./sounds/planet-gb.mp3",
    },
    {
      category: "space",
      word: "satellite",
      translation: "სატელიტი",
      image: "./images/satellite.svg",
      audioSrc: "./sounds/satellite-gb.mp3",
    },
    {
      category: "space",
      word: "astronaut",
      translation: "ასტრონავტი",
      image: "./images/astronaut.svg",
      audioSrc: "./sounds/astronaut-gb.mp3",
    },
    {
      category: "space",
      word: "earth",
      translation: "დედამიწა",
      image: "./images/earth.svg",
      audioSrc: "./sounds/earth-gb.mp3",
    },
    {
      category: "space",
      word: "telescope",
      translation: "ტელესკოპი",
      image: "./images/telescope.svg",
      audioSrc: "./sounds/telescope-gb.mp3",
    },
  ],
  [
    {
      category: "food",
      word: "apple",
      translation: "ვაშლი",
      image: "./images/apple.svg",
      audioSrc: "./sounds/apple-gb.mp3",
    },
    {
      category: "food",
      word: "banana",
      translation: "ბანანი",
      image: "./images/banana.svg",
      audioSrc: "./sounds/banana-gb.mp3",
    },
    {
      category: "food",
      word: "fish",
      translation: "თევზი",
      image: "./images/fish.svg",
      audioSrc: "./sounds/fish-gb.mp3",
    },
    {
      category: "food",
      word: "bread",
      translation: "პური",
      image: "./images/bread.svg",
      audioSrc: "./sounds/bread-gb.mp3",
    },
    {
      category: "food",
      word: "groceries",
      translation: "პროდუქტი",
      image: "./images/groceries.svg",
      audioSrc: "./sounds/groceries-gb.mp3",
    },
    {
      category: "food",
      word: "cheese",
      translation: "ყველი",
      image: "./images/cheese.svg",
      audioSrc: "./sounds/cheese-gb.mp3",
    },
    {
      category: "food",
      word: "pumpkin",
      translation: "გოგრა",
      image: "./images/pumpkin.svg",
      audioSrc: "./sounds/pumpkin-gb.mp3",
    },
    {
      category: "food",
      word: "shrimp",
      translation: "კრევეტი",
      image: "./images/shrimp.svg",
      audioSrc: "./sounds/shrimp-gb.mp3",
    },
  ],
  [
    {
      category: "animals",
      word: "chick",
      translation: "წიწილა",
      image: "./images/chick.svg",
      audioSrc: "./sounds/chick-gb.mp3",
    },
    {
      category: "animals",
      word: "whale",
      translation: "ვეშაპი",
      image: "./images/whale.svg",
      audioSrc: "./sounds/whale-gb.mp3",
    },
    {
      category: "animals",
      word: "pig",
      translation: "ღორი",
      image: "./images/pig.svg",
      audioSrc: "./sounds/pig-gb.mp3",
    },
    {
      category: "animals",
      word: "fox",
      translation: "მელია",
      image: "./images/fox.svg",
      audioSrc: "./sounds/fox-gb.mp3",
    },
    {
      category: "animals",
      word: "koala",
      translation: "კოალა",
      image: "./images/koala.svg",
      audioSrc: "./sounds/koala-gb.mp3",
    },
    {
      category: "animals",
      word: "tiger",
      translation: "ვეფხვი",
      image: "./images/tiger.svg",
      audioSrc: "./sounds/tiger-gb.mp3",
    },
    {
      category: "animals",
      word: "crab",
      translation: "კიბორჩხალა",
      image: "./images/crab.svg",
      audioSrc: "./sounds/crab-gb.mp3",
    },
    {
      category: "animals",
      word: "bull",
      translation: "ხარი",
      image: "./images/bull.svg",
      audioSrc: "./sounds/bull-gb.mp3",
    },
  ],
  [
    {
      category: "body",
      word: "head",
      translation: "თავი",
      image: "./images/head.svg",
      audioSrc: "./sounds/head-gb.mp3",
    },
    {
      category: "body",
      word: "neck",
      translation: "კისერი",
      image: "./images/neck.svg",
      audioSrc: "./sounds/neck-gb.mp3",
    },
    {
      category: "body",
      word: "hand",
      translation: "ხელი",
      image: "./images/hand.svg",
      audioSrc: "./sounds/hand-gb.mp3",
    },
    {
      category: "body",
      word: "nose",
      translation: "ცხვირი",
      image: "./images/nose.svg",
      audioSrc: "./sounds/nose-gb.mp3",
    },
    {
      category: "body",
      word: "skull",
      translation: "თავის ქალა",
      image: "./images/skull.svg",
      audioSrc: "./sounds/skull-gb.mp3",
    },
    {
      category: "body",
      word: "ear",
      translation: "ყური",
      image: "./images/ear.svg",
      audioSrc: "./sounds/ear-gb.mp3",
    },
    {
      category: "body",
      word: "tooth",
      translation: "კბილი",
      image: "./images/tooth.svg",
      audioSrc: "./sounds/tooth-gb.mp3",
    },
    {
      category: "body",
      word: "stomach",
      translation: "მუცელი",
      image: "./images/stomach.svg",
      audioSrc: "./sounds/stomach-gb.mp3",
    },
  ],
  [
    {
      category: "nature",
      word: "forest",
      translation: "ტყე",
      image: "./images/forest.svg",
      audioSrc: "./sounds/forest-gb.mp3",
    },
    {
      category: "nature",
      word: "beach",
      translation: "სანაპირო",
      image: "./images/beach.svg",
      audioSrc: "./sounds/beach-gb.mp3",
    },
    {
      category: "nature",
      word: "lake",
      translation: "ტბა",
      image: "./images/lake.svg",
      audioSrc: "./sounds/lake-gb.mp3",
    },
    {
      category: "nature",
      word: "volcano",
      translation: "ვულკანი",
      image: "./images/volcano.svg",
      audioSrc: "./sounds/volcano-gb.mp3",
    },
    {
      category: "nature",
      word: "rainbow",
      translation: "ცისარტყელა",
      image: "./images/rainbow.svg",
      audioSrc: "./sounds/rainbow-gb.mp3",
    },
    {
      category: "nature",
      word: "desert",
      translation: "უდაბნო",
      image: "./images/desert.svg",
      audioSrc: "./sounds/desert-gb.mp3",
    },
    {
      category: "nature",
      word: "snow",
      translation: "თოვლი",
      image: "./images/snow.svg",
      audioSrc: "./sounds/snow-gb.mp3",
    },
    {
      category: "nature",
      word: "tree",
      translation: "ხე",
      image: "./images/tree.svg",
      audioSrc: "./sounds/tree-gb.mp3",
    },
  ],
  [
    {
      category: "activities",
      word: "learn",
      translation: "სწავლა",
      image: "./images/learn.svg",
      audioSrc: "./sounds/learn-gb.mp3",
    },
    {
      category: "activities",
      word: "read",
      translation: "კითხვა",
      image: "./images/read.svg",
      audioSrc: "./sounds/read-gb.mp3",
    },
    {
      category: "activities",
      word: "cry",
      translation: "ტირილი",
      image: "./images/cry.svg",
      audioSrc: "./sounds/cry-gb.mp3",
    },
    {
      category: "activities",
      word: "play",
      translation: "თამაში",
      image: "./images/play.svg",
      audioSrc: "./sounds/play-gb.mp3",
    },
    {
      category: "activities",
      word: "talk",
      translation: "საუბარი",
      image: "./images/talk.svg",
      audioSrc: "./sounds/talk-gb.mp3",
    },
    {
      category: "activities",
      word: "win",
      translation: "მოგება",
      image: "./images/win.svg",
      audioSrc: "./sounds/win-gb.mp3",
    },
    {
      category: "activities",
      word: "dance",
      translation: "ცეკვა",
      image: "./images/dance.svg",
      audioSrc: "./sounds/dance-gb.mp3",
    },
    {
      category: "activities",
      word: "swim",
      translation: "ცურვა",
      image: "./images/swim.svg",
      audioSrc: "./sounds/swim-gb.mp3",
    },
  ],
  [
    {
      category: "colors",
      word: "white",
      translation: "თეთრი",
      image: "./images/white.svg",
      audioSrc: "./sounds/white-gb.mp3",
    },
    {
      category: "colors",
      word: "yellow",
      translation: "ყვითელი",
      image: "./images/yellow.svg",
      audioSrc: "./sounds/yellow-gb.mp3",
    },
    {
      category: "colors",
      word: "orange",
      translation: "სტაფილოსფერი",
      image: "./images/orange.svg",
      audioSrc: "./sounds/orange-gb.mp3",
    },
    {
      category: "colors",
      word: "red",
      translation: "წითელი",
      image: "./images/red.svg",
      audioSrc: "./sounds/red-gb.mp3",
    },
    {
      category: "colors",
      word: "purple",
      translation: "იასამნისფერი",
      image: "./images/purple.svg",
      audioSrc: "./sounds/purple-gb.mp3",
    },
    {
      category: "colors",
      word: "blue",
      translation: "ლურჯი",
      image: "./images/blue.svg",
      audioSrc: "./sounds/blue-gb.mp3",
    },
    {
      category: "colors",
      word: "green",
      translation: "მწვანე",
      image: "./images/green.svg",
      audioSrc: "./sounds/green-gb.mp3",
    },
    {
      category: "colors",
      word: "brown",
      translation: "ყავისფერი",
      image: "./images/brown.svg",
      audioSrc: "./sounds/brown-gb.mp3",
    },
  ],
  [
    {
      category: "family",
      word: "family",
      translation: "ოჯახი",
      image: "./images/family.svg",
      audioSrc: "./sounds/family-gb.mp3",
    },
    {
      category: "family",
      word: "mother",
      translation: "დედა",
      image: "./images/mother.svg",
      audioSrc: "./sounds/mother-gb.mp3",
    },
    {
      category: "family",
      word: "father",
      translation: "მამა",
      image: "./images/father.svg",
      audioSrc: "./sounds/father-gb.mp3",
    },
    {
      category: "family",
      word: "sister",
      translation: "და",
      image: "./images/sister.svg",
      audioSrc: "./sounds/sister-gb.mp3",
    },
    {
      category: "family",
      word: "brother",
      translation: "ძმა",
      image: "./images/brother.svg",
      audioSrc: "./sounds/brother-gb.mp3",
    },
    {
      category: "family",
      word: "pet",
      translation: "შინაური ცხოველი",
      image: "./images/pet.svg",
      audioSrc: "./sounds/pet-gb.mp3",
    },
    {
      category: "family",
      word: "grandma",
      translation: "ბებო",
      image: "./images/grandma.svg",
      audioSrc: "./sounds/grandma-gb.mp3",
    },
    {
      category: "family",
      word: "grandpa",
      translation: "ბაბუ",
      image: "./images/grandpa.svg",
      audioSrc: "./sounds/grandpa-gb.mp3",
    },
  ],
];

export { cards, mainCards };
